// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLPSDe8-OcMtv25Zy0yqzyRi1Ac76VfU',
    appId: '1:361129179339:web:72108bf17e31146ac1034e',
    messagingSenderId: '361129179339',
    projectId: 'sellersapp-e5619',
    authDomain: 'sellersapp-e5619.firebaseapp.com',
    storageBucket: 'sellersapp-e5619.appspot.com',
    measurementId: 'G-JQW83J52MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAU__sRleBl5zcmZU3Qbb8naYob8Zrnkk',
    appId: '1:361129179339:android:2f57a448585de85fc1034e',
    messagingSenderId: '361129179339',
    projectId: 'sellersapp-e5619',
    storageBucket: 'sellersapp-e5619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSyYyfeXmUjZt1tpveWCg1OQO3l2JIT8',
    appId: '1:361129179339:ios:b0a1ca2d10622421c1034e',
    messagingSenderId: '361129179339',
    projectId: 'sellersapp-e5619',
    storageBucket: 'sellersapp-e5619.appspot.com',
    iosBundleId: 'com.example.ridersapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSyYyfeXmUjZt1tpveWCg1OQO3l2JIT8',
    appId: '1:361129179339:ios:13ec4748ff8bd57dc1034e',
    messagingSenderId: '361129179339',
    projectId: 'sellersapp-e5619',
    storageBucket: 'sellersapp-e5619.appspot.com',
    iosBundleId: 'com.example.ridersapp.RunnerTests',
  );
}
